### PR TITLE
Samplefunctionaltest

### PR DESCRIPTION
**Pull request by lawrence-lee**
try this out!

you can run a test using

./gradlew runPoshi

I think it only works with firefox 38 though.

### CODE REVIEW

**Comment by gamerson** [comment]
do I need to have firefox 38 installed?

On Tue, Mar 29, 2016 at 4:11 PM, Lawrence Lee notifications@github.com
wrote:

> try this out!
> 
> you can run a test using
> 
> ./gradlew runPoshi
> 
> ## I think it only works with firefox 38 though.
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/gamerson/liferay-workspace/pull/4
> Commit Summary
> - Sample Functional Tests
> - Update gradle.properties to latest release
> - Missing Poshi Property
> 
> File Changes
> - _M_ gradle.properties
>   https://github.com/gamerson/liferay-workspace/pull/4/files#diff-0
>   (7)
> - _M_ modules/apps/sample-portlet/build.gradle
>   https://github.com/gamerson/liferay-workspace/pull/4/files#diff-1
>   (30)
> - _A_ modules/apps/sample-portlet/poshi-runner.properties
>   https://github.com/gamerson/liferay-workspace/pull/4/files#diff-2
>   (4)
> - _A_
>   modules/apps/sample-portlet/src/testFunctional/functions/AssertClick.function
>   https://github.com/gamerson/liferay-workspace/pull/4/files#diff-3
>   (19)
> - _A_
>   modules/apps/sample-portlet/src/testFunctional/functions/AssertText.function
>   https://github.com/gamerson/liferay-workspace/pull/4/files#diff-4
>   (9)
> - _A_
>   modules/apps/sample-portlet/src/testFunctional/functions/AssertVisible.function
>   https://github.com/gamerson/liferay-workspace/pull/4/files#diff-5
>   (7)
> - _A_
>   modules/apps/sample-portlet/src/testFunctional/functions/Click.function
>   https://github.com/gamerson/liferay-workspace/pull/4/files#diff-6
>   (6)
> - _A_
>   modules/apps/sample-portlet/src/testFunctional/functions/Open.function
>   https://github.com/gamerson/liferay-workspace/pull/4/files#diff-7
>   (5)
> - _A_
>   modules/apps/sample-portlet/src/testFunctional/functions/Pause.function
>   https://github.com/gamerson/liferay-workspace/pull/4/files#diff-8
>   (5)
> - _A_
>   modules/apps/sample-portlet/src/testFunctional/functions/Type.function
>   https://github.com/gamerson/liferay-workspace/pull/4/files#diff-9
>   (16)
> - _A_
>   modules/apps/sample-portlet/src/testFunctional/paths/SamplePortlet.path
>   https://github.com/gamerson/liferay-workspace/pull/4/files#diff-10
>   (24)
> - _A_
>   modules/apps/sample-portlet/src/testFunctional/tests/SamplePortlet.testcase
>   https://github.com/gamerson/liferay-workspace/pull/4/files#diff-11
>   (25)
> 
> Patch Links:
> - https://github.com/gamerson/liferay-workspace/pull/4.patch
> - https://github.com/gamerson/liferay-workspace/pull/4.diff
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/gamerson/liferay-workspace/pull/4

## 

Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by lawrence-lee** [comment]
Yea unfortunately. PoshiRunner uses an older version of Selenium Webdriver. They're updating, but i dont know how soon that will be.

**Comment by lawrence-lee** [comment]
in the properties file, you can try

```
browser.type=googlechrome
```

**Comment by gamerson** [comment]
Is there any way that poshiRunner could bundle the required version,
install it locally in the gradle build folder and exec that?

On Tue, Mar 29, 2016 at 4:39 PM, Lawrence Lee notifications@github.com
wrote:

> Yea unfortunately. PoshiRunner uses an older version of Selenium
> Webdriver. They're updating, but i dont know how soon that will be.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/gamerson/liferay-workspace/pull/4#issuecomment-203122001

## 

Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by gamerson** [comment]
I think requiring users to have a specific version of Firefox installed is
too big of a roadblock to its use.

On Tue, Mar 29, 2016 at 4:41 PM, Greg Amerson gregory.amerson@liferay.com
wrote:

> Is there any way that poshiRunner could bundle the required version,
> install it locally in the gradle build folder and exec that?
> 
> On Tue, Mar 29, 2016 at 4:39 PM, Lawrence Lee notifications@github.com
> wrote:
> 
> > Yea unfortunately. PoshiRunner uses an older version of Selenium
> > Webdriver. They're updating, but i dont know how soon that will be.
> > 
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > https://github.com/gamerson/liferay-workspace/pull/4#issuecomment-203122001
> 
> ## 
> 
> Greg Amerson
> Liferay Developer Tools
> Liferay, Inc. www.liferay.com

## 

Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by gamerson** [comment]
But that also requires chrome installed.  I think if we want to make this
generally usuable we need to have poshiRunner download its requirements.
However, perhaps that is too much of an investment at this point.  WE would
have to check with andrea on how much work that may be.

On Tue, Mar 29, 2016 at 4:41 PM, Lawrence Lee notifications@github.com
wrote:

> in the properties file, you can try
> 
> browser.type=googlechrome
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/gamerson/liferay-workspace/pull/4#issuecomment-203122649

## 

Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by gamerson** [comment]
Also can you rebase this on lastest workspace master?  thanks!

**Pull request closed without merging**
