### PR TITLE
add liferay-gradle-build-lang-plugin required parameters

### PR DESCRIPTION
**Pull request by lovettli**

### CODE REVIEW

**Comment by gamerson** [comment]
Hey Lovett,

Did you find that the buildLang task doesn't work unless these two
properties are specified?

On Thu, Jan 7, 2016 at 2:30 AM, Lovett Li notifications@github.com wrote:

> ---
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/gamerson/liferay-workspace/pull/1
> Commit Summary
> - fix mysql driver name in templates
> - gradle bundle info from gradle.properties
> - add liferay-gradle-build-lang-plugin required parameters
> 
> File Changes
> - _M_ build.gradle
>   https://github.com/gamerson/liferay-workspace/pull/1/files#diff-0
>   (13)
> - _M_ configs/dev/portal-ext.properties
>   https://github.com/gamerson/liferay-workspace/pull/1/files#diff-1
>   (4)
> - _M_ configs/local/portal-ext.properties
>   https://github.com/gamerson/liferay-workspace/pull/1/files#diff-2
>   (4)
> - _M_ configs/prod/portal-ext.properties
>   https://github.com/gamerson/liferay-workspace/pull/1/files#diff-3
>   (4)
> - _M_ configs/uat/portal-ext.properties
>   https://github.com/gamerson/liferay-workspace/pull/1/files#diff-4
>   (4)
> - _M_ gradle.properties
>   https://github.com/gamerson/liferay-workspace/pull/1/files#diff-5
>   (4)
> - _M_ settings.gradle
>   https://github.com/gamerson/liferay-workspace/pull/1/files#diff-6
>   (8)
> 
> Patch Links:
> - https://github.com/gamerson/liferay-workspace/pull/1.patch
> - https://github.com/gamerson/liferay-workspace/pull/1.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gamerson/liferay-workspace/pull/1.

## 

Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by lovettli** [comment]
Yes. i looked at liferay-gradle-build-lang-plugin. it will need these properties.  That will show this error "No value has been specified for property 'translateClientId'" If task lose these properties.

**Comment by gamerson** [comment]
@david-truong can we add this to the plugin?

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/david-truong/liferay-workspace/pull/23. <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Pull request closed without merging**
